### ISSUE TITLE
enableVibrateFallback default vibration not working on iphone 6s

### ISSUE THREAD

**Issue by hamoudaarfaoui** [junina-de/react-native-haptic-feedback#48]
when setting enableVibrateFallback true on IPHONE 6s is not playing the default or any kind of vibration,  is it supposed to be working ?

**Comment by mkuczera** [comment]
Hi, can you verify that it´s not the same as mentioned here? https://github.com/milk-and-cookies-io/react-native-haptic-feedback/issues/48

I got no iPhone6s available to test it. Back then it was possible and available

**Comment by nelsonprsousa** [comment]
@mkuczera Perhaps you confused github's issue?

**Comment by hamoudaarfaoui** [comment]
@mkuczera do u refer to another issue ?
