### ISSUE TITLE
Autolinking?

### ISSUE THREAD

**Issue by Guuz** [junina-de/react-native-haptic-feedback#53]
Is it possible for this package to enable React Native Autolinking? https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

Not sure what would be needed for it, but since almost every package out there these days does it, it shouldn't be that hard i guess ;-)

Now we always get this error when running/building the app:
![image](https://user-images.githubusercontent.com/810327/87313497-3fe8c200-c522-11ea-99db-6bda4d597795.png)
How do others deal with this? Just ignore it? ^_^

Edit: Android autolinking works. It only needs a few changes for iOS (podfiles). We now use this to mute the error: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library

**Comment by pabloluz** [comment]
Auto-linking is already implemented.

**Comment by woodrufs** [comment]
I installed this lib using auto linking on Android and iOS no problem today using react-native 0.63.4.
