### ISSUE TITLE
Calling haptic too frequently seems to cause crash

### ISSUE THREAD

**Issue by Daavidaviid** [junina-de/react-native-haptic-feedback#54]
Hi,

I'm creating a swipe selector for a project and I was using this library to get a native feedback on iOS device, and it seems that when I swipe too quickly this library is called many times and it is causing some issues, causing the app to crash. 

```
Enqueued from CHHapticEngineDispatchQueue
```

Anyone got this before ?

**Comment by mkuczera** [comment]
Hi, actually the library was enhanced with a queue at version 1.10.0.
Also while trying out i couldn´t reproduce it. If this is still an issue: can you attach the full error message and if available the corresponding xcode log?
