### ISSUE TITLE
Requesting clarity on this library vs. React Native's Vibration API

### ISSUE THREAD

**Issue by trackwell-mike** [junina-de/react-native-haptic-feedback#57]
I wanted to see what the difference is in this library vs. [React Native's Vibration API](https://reactnative.dev/docs/vibration). Thanks!

**Comment by trackwell-mike** [comment]
After further research, it appears the main difference is the ability to attach the feedback to an `onpress` event, rather than as a callback, like Vibration. 

Let me know if there is something else I missing.

**Comment by hugoh59** [comment]
Vibration and haptic feedback are 2 different things no? For me this library does not work tho, not haptic feedback is received.

**Comment by mkuczera** [comment]
Hi. These are indeed 2 different things. A haptic should be used for slight interaction feedback and is much less intense than the vibration.

This library is using also vibration as a fallback to mimic the behaviour for devices not able to perform haptic feedback.
