### ISSUE TITLE
Support rigid impact type

### ISSUE THREAD

**Issue by waltermvp** [junina-de/react-native-haptic-feedback#61]
Can this library support rigid haptic feedback on iOS?

https://developer.apple.com/documentation/uikit/uiimpactfeedbackstyle/uiimpactfeedbackstylerigid

**Comment by mkuczera** [comment]
Not yet, will support rigid and soft as new types within the next release

**Comment by mkuczera** [comment]
Hi @waltermvp , i just published 1.12.0-beta.0 . Can you verify that everything is working?

**Comment by waltermvp** [comment]
It's working, thank you for this enhancement.
