### ISSUE TITLE
minSdkVersion is hard-coded

### ISSUE THREAD

**Issue by plaa** [junina-de/react-native-haptic-feedback#62]
The library has hard-coded `minSdkVersion` to be 16, instead of pulling it from the root project. This causes our Android Detox build to fail. (Not sure why the main build works but Detox build fails.)

I have a PR to fix the issue. In the meantime one can use `"react-native-haptic-feedback": "github:plaa/react-native-haptic-feedback"`

**Comment by mkuczera** [comment]
Awesome. Thank you, i will include this with the next release
