### ISSUE TITLE
Not working on IOS 14.4, RN 0.64

### ISSUE THREAD

**Issue by benson7667** [junina-de/react-native-haptic-feedback#64]
I follow the guide for installation and the code snippet.
I get the error warning as below even I have try with different method:
```
WARN  RNReactNativeHapticFeedback is not available
```

```
const options = {
  enableVibrateFallback: true,
  ignoreAndroidSystemSettings: false,
};

ReactNativeHapticFeedback.trigger('selection', options); // selection | impactLight and etc.....
```

**Comment by ivanszhuravlev** [comment]
> I follow the guide for installation and the code snippet.
> I get the error warning as below even I have try with different method:
> 
> ```
> WARN  RNReactNativeHapticFeedback is not available
> ```
> 
> ```
> const options = {
>   enableVibrateFallback: true,
>   ignoreAndroidSystemSettings: false,
> };
> 
> ReactNativeHapticFeedback.trigger('selection', options); // selection | impactLight and etc.....
> ```

Hi, `cd ios && pod install` fixed it for me

**Comment by ivanszhuravlev** [comment]
But not for everyone, as I can see https://github.com/junina-de/react-native-haptic-feedback/issues/39

**Comment by fernando-orchata** [comment]
Hi! for me is also not working

I'm using RN 0.64 and testing on iPhone 12 iOS 14.5.1

**Comment by woohoou** [comment]
Same here iOS 14.4.2.

**Comment by benson7667** [comment]
hey, if someone can try out the method in the comment? I haven't try that.

https://stackoverflow.com/questions/43760502/enable-haptic-feedback-on-react-native-touchable-view/59925020#59925020

https://github.com/junina-de/react-native-haptic-feedback/issues/40

**Comment by woohoou** [comment]
Sorry! I made a silly mistake, the library is working fine for me even without try out the method in the comment.
